#!/usr/bin/env python3
"""
Interactive setup script for Ticket Price Tracker.
Guides users through configuration step by step.
"""

import os
import sys
import shutil
from pathlib import Path


def print_header():
    print("\n" + "=" * 60)
    print("   TICKET PRICE TRACKER - Setup Wizard")
    print("=" * 60)
    print()


def setup_env():
    """Set up the .env file with user credentials."""
    env_path = Path(".env")
    if env_path.exists():
        overwrite = input(".env already exists. Overwrite? (y/N): ").strip().lower()
        if overwrite != "y":
            print("Keeping existing .env file.")
            return

    print("\n--- Step 1: SeatGeek API Key ---")
    print("Get your free API key at: https://seatgeek.com/account/develop")
    print("(Press Enter to skip if you don't have one yet)\n")
    sg_client_id = input("SeatGeek Client ID: ").strip()
    sg_client_secret = input("SeatGeek Client Secret (optional): ").strip()

    print("\n--- Step 2: SMS Alerts (FREE via Email-to-SMS Gateway) ---")
    print("This uses your email to send texts through your carrier's gateway.")
    print("No Twilio, no paid service — completely free!\n")

    print("For Gmail: enable 2FA, then create an App Password at:")
    print("  https://myaccount.google.com/apppasswords")
    print("(Press Enter to skip if you want to set this up later)\n")

    smtp_email = input("Your email address (e.g., you@gmail.com): ").strip()
    smtp_password = ""
    if smtp_email:
        smtp_password = input("App Password (16-char code from Google): ").strip()

    print("\n  Supported carriers:")
    print("  US:     att, tmobile, verizon, sprint, uscellular, metropcs,")
    print("          boost, cricket, mint, googlefi, visible, xfinity")
    print("  Canada: rogers, bell, telus, fido, koodo\n")

    phone_number = input("Your phone number (digits only, e.g., 5551234567): ").strip()
    carrier = input("Your carrier (e.g., verizon, att, tmobile): ").strip().lower()

    # Determine SMTP provider from email
    smtp_provider = "gmail"
    if smtp_email:
        if "outlook" in smtp_email or "hotmail" in smtp_email or "live.com" in smtp_email:
            smtp_provider = "outlook"
        elif "yahoo" in smtp_email:
            smtp_provider = "yahoo"
        elif "icloud" in smtp_email or "me.com" in smtp_email:
            smtp_provider = "icloud"

    # Write .env file
    with open(env_path, "w") as f:
        f.write("# Ticket Price Tracker - Environment Variables\n")
        f.write("# Generated by setup.py\n\n")
        f.write(f"SEATGEEK_CLIENT_ID={sg_client_id}\n")
        f.write(f"SEATGEEK_CLIENT_SECRET={sg_client_secret}\n\n")
        f.write("# Ticketmaster Discovery API (optional, improves results)\n")
        f.write("TICKETMASTER_API_KEY=\n\n")
        f.write("# SMS Alerts via Email-to-SMS Gateway (FREE)\n")
        f.write(f"SMTP_EMAIL={smtp_email}\n")
        f.write(f"SMTP_PASSWORD={smtp_password}\n")
        f.write(f"PHONE_NUMBER={phone_number}\n")
        f.write(f"PHONE_CARRIER={carrier}\n")

    print(f"\n.env file created at: {env_path.absolute()}")


def setup_config():
    """Set up the config.yaml with watched events."""
    print("\n--- Step 3: Add Events to Watch ---")
    print("You can add events to monitor. Each needs a search query")
    print("and optionally a target price for SMS alerts.\n")

    events = []
    while True:
        query = input("Event to track (or press Enter to finish): ").strip()
        if not query:
            break

        max_price = input(f"  Target max price for '{query}' (or Enter to skip): ").strip()
        city = input(f"  City filter (or Enter to skip): ").strip()
        qty = input(f"  Number of tickets (default 2): ").strip()
        event_type = input(f"  Type (sports/concert/theater, or Enter to skip): ").strip()

        event = {"query": query}
        if max_price:
            event["max_price"] = float(max_price)
        if city:
            event["city"] = city
        if qty:
            event["quantity"] = int(qty)
        if event_type in ("sports", "concert", "theater"):
            event["event_type"] = event_type

        events.append(event)
        print(f"  Added '{query}' to watchlist!\n")

    if events:
        # Update config file with new events
        print(f"\nAdded {len(events)} events to your watchlist.")
        print("You can edit config/config.yaml to modify them later.")


def setup_directories():
    """Ensure required directories exist."""
    Path("data").mkdir(exist_ok=True)
    Path("config").mkdir(exist_ok=True)
    print("Directories created: data/, config/")


def install_dependencies():
    """Install Python dependencies."""
    print("\n--- Step 4: Install Dependencies ---")
    install = input("Install Python dependencies now? (Y/n): ").strip().lower()
    if install != "n":
        os.system(f"{sys.executable} -m pip install -r requirements.txt")
        print("\nDependencies installed!")
    else:
        print("Skipped. Run 'pip install -r requirements.txt' when ready.")


def print_next_steps():
    """Print next steps for the user."""
    print("\n" + "=" * 60)
    print("   SETUP COMPLETE!")
    print("=" * 60)
    print()
    print("Next steps:")
    print("  1. Edit config/config.yaml to customize your watched events")
    print("  2. Test your SMS setup:")
    print("     python main.py --test-sms")
    print("  3. Run a single price check:")
    print("     python main.py")
    print("  4. Start continuous monitoring:")
    print("     python main.py --schedule")
    print()
    print("Tips:")
    print("  - Use --verbose flag for detailed logging")
    print("  - Check status anytime: python main.py --status")
    print("  - Add events via CLI: python main.py --add 'Artist Name' --max-price 200")
    print("  - For 24/7 monitoring, use cron or systemd (see README)")
    print()


def main():
    print_header()
    setup_directories()
    setup_env()
    setup_config()
    install_dependencies()
    print_next_steps()


if __name__ == "__main__":
    main()
