#!/usr/bin/env python3
"""
Interactive setup script for Ticket Price Tracker.
Guides users through configuration step by step.
"""

import os
import sys
import shutil
from pathlib import Path


def print_header():
    print("\n" + "=" * 60)
    print("   TICKET PRICE TRACKER - Setup Wizard")
    print("=" * 60)
    print()


def setup_env():
    """Set up the .env file with user credentials."""
    env_path = Path(".env")
    if env_path.exists():
        overwrite = input(".env already exists. Overwrite? (y/N): ").strip().lower()
        if overwrite != "y":
            print("Keeping existing .env file.")
            return

    print("\n--- Step 1: SeatGeek API Key ---")
    print("Get your free API key at: https://seatgeek.com/account/develop")
    print("(Press Enter to skip if you don't have one yet)\n")
    sg_client_id = input("SeatGeek Client ID: ").strip()
    sg_client_secret = input("SeatGeek Client Secret (optional): ").strip()

    print("\n--- Step 2: Twilio SMS Setup ---")
    print("Sign up at: https://www.twilio.com (free trial = $15 credit)")
    print("Find credentials at: https://console.twilio.com")
    print("(Press Enter to skip if you don't have one yet)\n")
    twilio_sid = input("Twilio Account SID: ").strip()
    twilio_token = input("Twilio Auth Token: ").strip()
    twilio_from = input("Twilio Phone Number (e.g., +15551234567): ").strip()
    twilio_to = input("Your Phone Number (e.g., +15559876543): ").strip()

    # Write .env file
    with open(env_path, "w") as f:
        f.write("# Ticket Price Tracker - Environment Variables\n")
        f.write("# Generated by setup.py\n\n")
        f.write(f"SEATGEEK_CLIENT_ID={sg_client_id}\n")
        f.write(f"SEATGEEK_CLIENT_SECRET={sg_client_secret}\n\n")
        f.write(f"TWILIO_ACCOUNT_SID={twilio_sid}\n")
        f.write(f"TWILIO_AUTH_TOKEN={twilio_token}\n")
        f.write(f"TWILIO_FROM_NUMBER={twilio_from}\n")
        f.write(f"TWILIO_TO_NUMBER={twilio_to}\n")

    print(f"\n.env file created at: {env_path.absolute()}")


def setup_config():
    """Set up the config.yaml with watched events."""
    print("\n--- Step 3: Add Events to Watch ---")
    print("You can add events to monitor. Each needs a search query")
    print("and optionally a target price for alerts.\n")

    events = []
    while True:
        query = input("Event to track (or press Enter to finish): ").strip()
        if not query:
            break

        max_price = input(f"  Target max price for '{query}' (or Enter to skip): ").strip()
        city = input(f"  City filter (or Enter to skip): ").strip()
        qty = input(f"  Number of tickets (default 2): ").strip()
        event_type = input(f"  Type (sports/concert/theater, or Enter to skip): ").strip()

        event = {"query": query}
        if max_price:
            event["max_price"] = float(max_price)
        if city:
            event["city"] = city
        if qty:
            event["quantity"] = int(qty)
        if event_type in ("sports", "concert", "theater"):
            event["event_type"] = event_type

        events.append(event)
        print(f"  Added '{query}' to watchlist!\n")

    if events:
        # Update config file with new events
        print(f"\nAdded {len(events)} events to your watchlist.")
        print("You can edit config/config.yaml to modify them later.")


def setup_directories():
    """Ensure required directories exist."""
    Path("data").mkdir(exist_ok=True)
    Path("config").mkdir(exist_ok=True)
    print("Directories created: data/, config/")


def install_dependencies():
    """Install Python dependencies."""
    print("\n--- Step 4: Install Dependencies ---")
    install = input("Install Python dependencies now? (Y/n): ").strip().lower()
    if install != "n":
        os.system(f"{sys.executable} -m pip install -r requirements.txt")
        print("\nDependencies installed!")
    else:
        print("Skipped. Run 'pip install -r requirements.txt' when ready.")


def print_next_steps():
    """Print next steps for the user."""
    print("\n" + "=" * 60)
    print("   SETUP COMPLETE!")
    print("=" * 60)
    print()
    print("Next steps:")
    print("  1. Edit config/config.yaml to customize your watched events")
    print("  2. Test your SMS setup:")
    print("     python main.py --test-sms")
    print("  3. Run a single price check:")
    print("     python main.py")
    print("  4. Start continuous monitoring:")
    print("     python main.py --schedule")
    print()
    print("Tips:")
    print("  - Use --verbose flag for detailed logging")
    print("  - Check status anytime: python main.py --status")
    print("  - Add events via CLI: python main.py --add 'Artist Name' --max-price 200")
    print("  - For 24/7 monitoring, use cron or systemd (see README)")
    print()


def main():
    print_header()
    setup_directories()
    setup_env()
    setup_config()
    install_dependencies()
    print_next_steps()


if __name__ == "__main__":
    main()
